controllers/ProductController.php
<?php

namespace skmnt\skyadmin\shop\controllers;

use Yii;
use yii\web\Controller;
use common\models\Product;
use skmnt\skyadmin\shop\models\ProductSearch;

class ProductController extends Controller
{
    use \admin\components\ControllerTrait;
    use \admin\components\ControllerCUDTrait;
    use \admin\components\ControllerBulkActionTrait;
    use \skmnt\skyadmin\shop\components\DataExportTrait;

    private $type;
    private $baseClass = Product::class;
    private $searchClass = ProductSearch::class;
    private $rootController = '/skyadmin-shop/product';

    public function actionIndex($download = false)
    {
        $searchModel = new $this->searchClass();
        $dataProvider = $searchModel->search(\Yii::$app->request->queryParams);

        if ($download) {
            $this->downloadData($dataProvider, $searchModel);
            return $this->redirect(Url::current(['download' => null]));
        }

        return $this->render('index', [
            'title' => 'Товары',
            'searchModel' => $searchModel,
            'dataProvider' => $dataProvider,
        ]);
    }

    public function actionCreate()
    {
        return $this->actionUpdate(null, true);
    }

    public function actionUpdate($id, $__createMode = false)
    {
        if ($id === null && $__createMode === true) {
            $model = new $this->baseClass([
                'active' => \Yii::$app->st->defaultsNewProductActive_string('1'),
            ]);
        } else {
            $model = $this->findModel($id);
        }

        if (method_exists($model, 'propSave')) $model->propSave();

        if ($model->load(\Yii::$app->request->post()) && $model->preProcess() && $model->save()) {
            if (!isset($_POST['exitmode']))
                return $this->redirect(["{$this->rootController}/update", 'id' => $model->id]);    
            else {
                return $this->redirect(["{$this->rootController}/index"]);
            }
        } else {
            return $this->render($__createMode ? 'create' : 'update', [
                'model' => $model,
                'indexTitle' => 'Товары',
                'indexAction' => ["{$this->rootController}/index"],
                'indexSearchId' => (new $this->searchClass())->formName(),
            ]);
        }
    }

    public function actionBulkEdit()
    {
        $ids = Yii::$app->request->post('ids');
        $action = Yii::$app->request->post('action');

        $bulkForm = \yii\base\DynamicModel::validateData(compact('ids', 'action'), [
            ['ids', 'string', 'max' => 5000],
            ['action', 'string', 'max' => 50],
            ['ids', 'required', 'message' => 'Укажите список товаров (id-коды через запятую)']
        ]);

        if(!$bulkForm->hasErrors()) {
            return $this->render('bulk-edit', [
                'ids' => $bulkForm->ids,
                'model' => new Product,
            ]);
        }
        else {
            Yii::$app->session->setFlash('error', 'Ошибка в форме групповой обработки.<br><br>' . \yii\helpers\Html::errorSummary($bulkForm));
        }
        
        return $this->redirect(Yii::$app->request->referrer);
    }

    public function actionBulkEditSave()
    {
        $model = new Product;

        if ($model->load(Yii::$app->request->post()))
        {
            $attributes = [];
            foreach ($model->attributes as $key => $value) {
                $value = is_array($value) ? array_filter($value) : $value;
                if (!empty($value)) $attributes[$key] = $value;
            }

            if(empty($attributes)) {
                Yii::$app->session->setFlash('warning', 'Групповая обработка не выполнена, не заданы свойства для изменения.');
                return $this->redirect(['index']);
            }

            $_ids = explode(',', Yii::$app->request->post('ids')) ?: [];
            $_ids = array_unique(array_filter($_ids, 'trim'));

            if(empty($_ids)) {
                Yii::$app->session->setFlash('warning', 'Групповая обработка не выполнена, не заданы товары для изменения.');
                return $this->redirect(['index']);
            }

            foreach ($attributes as $key => $value) {
                Yii::$app->session->addFlash('info', 'Изменено: ' . "{$key} -> " . print_r($value, true));
            }

            foreach ($_ids as $pid) {
                $product = Product::findOne($pid);

                $newAttributes = array_replace_recursive($product->attributes, $attributes);
                array_walk_recursive($newAttributes, function(&$el, $key) {
                    if ($el == '!') $el = null;
                });
                $newAttributes['prop'] = array_filter($newAttributes['prop']);

                $product->attributes = $newAttributes;

                if(!$product->save()) {
                    throw new \yii\web\ServerErrorHttpException('Ошибка груп.обработки, товар #' . $pid);
                }
            }

            Yii::$app->session->setFlash('success', 'Групповая обработка завершена.');
            setcookie('group-id-list', null, time() - 1, '/');
        }

        return $this->redirect(['index']);
    }
}

controllers/UtilsController.php
<?php

namespace skmnt\skyadmin\shop\controllers;

use Yii;
use yii\helpers\Url;
use yii\helpers\Html;
use yii\web\Controller;
use common\models\Product;
use common\models\Dictionary;

class UtilsController extends Controller
{
    public function behaviors()
    {
        return [
            'access' => [
                'class' => \yii\filters\AccessControl::className(),
                'rules' => [
                    [
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
        ];
    }

    public function actionDictionaryTypedFeed($type, $q) {
        $out = ['results' => [['id' => '', 'text' => '']]];
        if ($q !== null) {
            $data = Dictionary::find()
                        ->select('id, title as text')
                        ->where(['like', 'title', $q])
                        ->andWhere(['type' => $type])
                        ->limit(15)
                        ->asArray()->all();

            $out['results'] = array_values($data);
        }
        return $this->asJson($out);
    }

    public function actionProductFamilyFeed($q)
    {
        $out = ['results' => [['id' => '', 'text' => '']]];
        if ($q !== null) {
            $data = product::find()
                        ->select('id, title as text')
                        ->where(['or', ['like', 'title', $q], ['id' => $q]])
                        ->limit(15)
                        ->asArray()->all();

            $out['results'] = array_values($data);
        }
        return $this->asJson($out);
    }

    public function actionDictionaryClean()
    {
        foreach (Dictionary::find()->where(['not', ['type' => 1]])->each() as $item) {
            $item->delete();
        }
        \Yii::$app->session->setFlash('success', 'Очистка справочников выполнена успешно.');
        return $this->redirect(['/admin']);
    }

    public function actionProductClean()
    {
        foreach (Product::find()->each() as $item) {
            $item->delete();
        }
        \Yii::$app->session->setFlash('success', 'Очистка каталога товаров выполнена успешно.');
        return $this->redirect(['/admin']);
    }
}

views/product/_form-bulk-edit.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\web\JsExpression;
use common\models\Dictionary;

/* @var $this yii\web\View */
/* @var $model common\models\Dictionary */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="panel with-image-aside">

    <?php $form = ActiveForm::begin(['id' => 'update-form', 'action' => ['bulk-edit-save']]); ?>

        <?= ($_errorHtml = $form->errorSummary($model)) ? '<div class="col-sm-12 text-danger">' . $_errorHtml . '</div>' : '' ?>

        <div class="panel-body">
            <div class="row">
                <?= \admin\widgets\form\DynamicForm::widget([
                    'form' => $form,
                    'model' => $model,
                    'overrideFields' => ['except' => ['slug']],
                    'bulkMode' => $bulkMode,
                ]) ?>
            </div>
        </div>

        <div class="panel-footer col-md-12" style="background-color: #222d32;">
            <?= Html::submitButton('Сохранить для всех', ['class' => 'btn btn-primary']) ?>
        </div>

        <?= Html::hiddenInput('ids', $_POST['ids']) ?>

    <?php ActiveForm::end(); ?>

    <div class="clearfix"></div>

</div>

views/product/_form.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use yii\web\JsExpression;
use common\models\Dictionary;

/* @var $this yii\web\View */
/* @var $model common\models\Dictionary */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="panel with-image-aside">

    <?php $form = ActiveForm::begin(['id' => 'update-form']); ?>

        <?= ($_errorHtml = $form->errorSummary($model)) ? '<div class="col-sm-12 text-danger">' . $_errorHtml . '</div>' : '' ?>

        <div class="panel-body">
            <div class="row">

                <?= $form->field($model, 'title', ['options' => ['class' => 'col-md-6']]) ?>

                <?= $form->field($model, 'family_id', ['options' => ['class' => 'col-md-4', 'style' => 'min-height: 69px;']])
                    ->widget(\kartik\select2\Select2::classname(), [
                        'options' => ['placeholder' => 'Поиск товара ...', 'multiple' => false],
                        'initValueText' => @\common\models\Product::findOne($model->family_id)['title'] ?: '- не найдено (ошибка) -',
                        'theme' => \kartik\select2\Select2::THEME_DEFAULT,
                        'pluginOptions' => [
                            'allowClear' => true,
                            'minimumInputLength' => 1,
                            'maximumInputLength' => 10,
                            'language' => 'ru',
                            'ajax' => [
                                'url' => Url::to(['utils/product-family-feed']),
                                'dataType' => 'json',
                                'delay' => 200,
                                'cache' => true,
                                'data' => new JsExpression('function(params) { return {q: params.term}; }')
                            ],
                            'escapeMarkup' => new JsExpression('function (markup) { return markup; }'),
                            'templateResult' => new JsExpression('function(item) { return item.text; }'),
                            'templateSelection' => new JsExpression('function (item) { return item.text; }'),
                        ]
                    ]) ?>

                <?= $form->field($model, 'active', ['options' => ['class' => 'col-md-2']])->dropDownList(['1' => 'Активен', '0' => 'Выключен']) ?>

                <div class="clearfix"></div>

                <?= $form->field($model, 'code', ['options' => ['class' => 'col-md-6']]) ?>

                <?= \admin\widgets\form\DynamicForm::widget(['form' => $form, 'model' => $model, 'seoMode' => false]) ?>
                
                <div class="col-sm-12"><hr></div>

                <?= \skmnt\skyadmin\shop\widgets\form\ProductDynamicForm::widget(['form' => $form, 'model' => $model]) ?>

            </div>
        </div>

        <div class="panel-footer col-md-12" style="background-color: #222d32;">
            <?= Html::a('Сохранить и закрыть', null, [
                'onclick' => 'SaveAndExit(this);',
                'class' => 'pull-right btn btn-success',
            ]) ?>
            <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="clearfix"></div>

</div>

views/product/_image.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Product */
/* @var $form yii\widgets\ActiveForm */

?>
<div>

    <?= \admin\widgets\form\ImageControl::widget(['model' => $model]) ?>

</div>

views/product/_seo.php
<?php

use yii\helpers\Url;
use yii\helpers\Html;
use yii\widgets\ActiveForm;
use common\models\Page;

/* @var $this yii\web\View */
/* @var $model common\models\Page */
/* @var $form yii\widgets\ActiveForm */
?>

<div class="panel with-image-aside">

    <?php $form = ActiveForm::begin(['id' => 'update-form']); ?>

        <?= ($_errorHtml = $form->errorSummary($model)) ? '<div class="col-sm-12 text-danger">'.$_errorHtml.'</div>' : '' ?>

        <div class="panel-body">
            <div class="row">

                <?= \admin\widgets\form\DynamicForm::widget(['form' => $form, 'model' => $model, 'seoMode' => true]) ?>

            </div>
        </div>

        <div class="panel-footer col-md-12" style="background-color: #222d32;">
            <?= Html::a('Сохранить и закрыть', null, [
                'onclick' => 'SaveAndExit(this);',
                'class' => 'pull-right btn btn-success',
            ]) ?>
            <?= Html::submitButton('Сохранить', ['class' => 'btn btn-primary']) ?>
        </div>

    <?php ActiveForm::end(); ?>

    <div class="clearfix"></div>

</div>

views/product/bulk-edit.php
<?php

use yii\helpers\Html;
use yii\widgets\ActiveForm;
use kartik\select2\Select2;

$this->title = 'Групповое изменение';
$this->params['breadcrumbs'][] = ['label' => 'Товары', 'url' => ['index']];
$this->params['breadcrumbs'][] = 'Групповое изменение';
?>

<div class="product-update">

<h2>Вы вносите изменение для группы товаров</h2>

<div class="well">
	<h4>Список ID-кодов</h4>
	<p style="word-break: break-all; max-height: 60px; overflow-y: scroll;"><?= $ids ?></p>
	<hr>
	<ol>
		<li>Задаются только те поля, что заданы.</li>
		<li>Чтобы сбросить значение - указать/выбрать "!"</li>
	</ol>
</div>

<div class="bulk-form">
	<?= $this->render('_form-bulk-edit', [
	    'model' => $model,
	    'ids' => $ids,
	    'bulkMode' => true,
	]) ?>
</div>

<style type="text/css">
	.bulk-form {
		padding: 0 15px;
	}
	.bulk-form > .row {
		padding-left: 4px;
		padding-right: 4px;
	}
</style>

views/product/create.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Dictionary */

$this->title = 'Создание - ' . $indexTitle;
$this->params['breadcrumbs'][] = ['label' => $indexTitle, 'url' => $indexAction];
$this->params['breadcrumbs'][] = 'Создание';
?>
<div class="custom-product-create">

    <?= \yii\bootstrap\Tabs::widget([
        'items' => [
            [
                'label' => 'Общее',
                'content' => $this->render('_form', ['model' => $model]),
                'active' => true,
                'options' => ['id' => 'general'],
            ],
            [
                'label' => 'Фото <small style="opacity: .7;">(необходимо сохранить запись)</small>',
                'url' => false,
                'encode' => false,
                'headerOptions' => ['class' => 'disabled', 'disable' => true],
            ],
        ],
    ]) ?>

</div>

views/product/index.php
<?php

use yii\helpers\Html;
use yii\helpers\StringHelper;
use admin\widgets\GridView2;
use kartik\select2\Select2;

/* @var $this yii\web\View */
/* @var $searchModel admin\models\DictionarySearch */
/* @var $dataProvider yii\data\ActiveDataProvider */

$this->title = 'Товар';
$this->params['breadcrumbs'][] = $this->title;
?>

<div class="product-index">

    <p>
        <?= Html::a('Создать', ['create'], ['class' => 'btn btn-success']) ?>
    </p>

    <?= GridView2::widget([
        'dataProvider' => $dataProvider,
        'filterModel' => $searchModel,
        'pager' => [
            'maxButtonCount' => 5,
            'prevPageLabel' => '<span class="glyphicon glyphicon-backward"></span>',
            'nextPageLabel' => '<span class="glyphicon glyphicon-forward"></span>',
            'firstPageLabel' => '<span class="glyphicon glyphicon-fast-backward"></span>',
            'lastPageLabel' => '<span class="glyphicon glyphicon-fast-forward"></span>',
            'options' => ['class' => 'pagination center'],
        ],
        'columns' => [
            ['class' => 'yii\grid\CheckboxColumn', 'headerOptions' => ['class' => 'checkbox-column'], 'contentOptions' => ['class' => 'checkbox-column']],
            'id',
            ['class' => 'admin\widgets\ControlColumn', 'template' => '{active}', 'headerOptions' => ['class' => 'control-column']],
            [
                'attribute' => 'title',
                'format' => 'raw',
                'value' => function($model, $key) {
                    return Html::a($model->title, ['/skyadmin-shop/product/update', 'id' => $model->id], ['class' => 'btn btn-sm btn-fw btn-title-link']);
                },
                'headerOptions' => ['class' => 'title-column'],
                'contentOptions' => ['class' => 'title-column'],
            ],
            [
                'attribute' => 'code',
                'headerOptions' => ['class' => 'code-column'],
                'contentOptions' => ['class' => 'code-column', 'style' => 'font-family: monospace; font-size: 90%; font-weight: bold;'],
            ],
            [
                'attribute' => 'p_category',
                'label' => 'Категория',
                'format' => 'raw',
                'filter' => \common\models\Dictionary::listByType(\common\models\Dictionary::T_PRODUCT_CATEGORY),
                'value' => function($model) { return $model->propValue(\common\models\Dictionary::T_PRODUCT_CATEGORY, 'category'); },
                'headerOptions' => ['class' => 'category-column'],
                'contentOptions' => ['class' => 'category-column'],
            ],
            [
                'attribute' => 'price',
                'format' => ['currency', 'RUR'],
                'headerOptions' => ['class' => 'price-column'],
                'contentOptions' => ['class' => 'price-column'],
            ],
            [
                'attribute' => 'price_old',
                'format' => ['currency', 'RUR'],
                'headerOptions' => ['class' => 'price-column'],
                'contentOptions' => ['class' => 'price-column'],
            ],
            [
                'attribute' => 'updated_at',
                'filter' => false,
                'format' => ['date', 'php:d-m-Y'],
                'headerOptions' => ['class' => 'date-column'],
                'contentOptions' => ['class' => 'date-column'],
            ],
            ['class' => 'admin\widgets\ControlColumn', 'headerOptions' => ['class' => 'delete-column'], 'template' => '{delete}'],
        ],
        'tableOptions' => ['class' => 'table table-striped table-bordered ' . ($_bulkFormClass = 'bulk-form-grid')]
    ]); ?>

    <?= (@$_GET['__ie']) ? $this->render('../../components/views/ie-control', ['dataProvider' => $dataProvider, 'target' => 'Product']) : '' ?>

    <?= \skmnt\skyadmin\shop\helpers\ProductBulkForm::widget(['bulkFormClass' => $_bulkFormClass]) ?>

</div>

views/product/update.php
<?php

use yii\helpers\Html;

/* @var $this yii\web\View */
/* @var $model common\models\Dictionary */

$this->title = sprintf('%s [#%d]', $_title = \yii\helpers\StringHelper::truncate($model->title, 60), $model->id);
$this->params['breadcrumbs'][] = ['label' => $indexTitle, 'url' => $indexAction];
$this->params['breadcrumbs'][] = $_title . ' (изменение)';
$this->params['breadcrumbs'][] = ['label' => '(Создать запись)', 'url' => @$createAction, 'encode' => false];
?>
<div class="custom-product-update">

    <?= \yii\bootstrap\Tabs::widget([
        'items' => [
            [
                'label' => 'Общее',
                'content' => $this->render('_form', ['model' => $model]),
                'active' => true,
                'options' => ['id' => 'general'],
            ],
            [
                'label' => 'Фото',
                'content' => $this->render('_image', ['model' => $model]),
                'options' => ['id' => 'image'],
            ],
            [
                'label' => '<i class="fa fa-cogs" style="font-size: 12px;"></i> SEO',
                'encode' => false,
                'content' => $this->render('_seo', ['model' => $model]),
                'options' => ['id' => 'seo'],
            ],
        ],
        'clientEvents' => [
            'show.bs.tab' => new \yii\web\JsExpression('function(e) { location.hash = e.target.hash; }'),
        ],
    ]) ?>

    <? $this->registerJs("var hash = window.location.hash; hash && $('ul.nav a[href=\"' + hash + '\"]').tab('show');"); ?>

</div>